# Generated by Django 3.2.11 on 2022-01-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='todotask',
        ),
    ]
